# Step 0 -- R clubSandwich HTZ on the same toy panel.
# Loads toy_panel.csv (generated by make_toy_panel.py), fits OLS,
# computes CR2 vcov clustered on pid, and runs Wald_test(test = "HTZ")
# for the joint H0: beta_x1 = beta_x2 = beta_x3 = 0 (q = 3).
# Writes scalars to step0_htz_r_out.txt at full precision for the
# cross-check against Stata reg_sandwich AHZ.

suppressPackageStartupMessages({
  library(clubSandwich)
})

cat("clubSandwich version: ", as.character(packageVersion("clubSandwich")), "\n", sep = "")
cat("R version          : ", R.version.string, "\n", sep = "")

df <- read.csv("toy_panel.csv")
stopifnot(nrow(df) == 80, length(unique(df$pid)) == 20)

m <- lm(y ~ x1 + x2 + x3 + z, data = df)
V_CR2 <- vcovCR(m, cluster = df$pid, type = "CR2")

# Joint test of x1 = x2 = x3 = 0.
constraint <- constrain_zero(c("x1", "x2", "x3"), coef(m))
res <- Wald_test(m, constraints = constraint, vcov = V_CR2, test = "HTZ")
print(res)

# Wald_test returns a data.frame with columns: test, Fstat, df_num, df_denom, p_val
stopifnot("HTZ" %in% res$test)
row <- res[res$test == "HTZ", ]

out <- c(
  sprintf("engine=r_clubSandwich"),
  sprintf("clubSandwich_version=%s", as.character(packageVersion("clubSandwich"))),
  sprintf("F_stat=%24.16e",   row$Fstat),
  sprintf("F_df1=%24.16e",    row$df_num),
  sprintf("F_df2=%24.16e",    row$df_denom),
  sprintf("F_pvalue=%24.16e", row$p_val),
  sprintf("N_obs=%24.16e",    nrow(df)),
  sprintf("N_clust=%24.16e",  length(unique(df$pid)))
)
writeLines(out, "step0_htz_r_out.txt")
cat("wrote step0_htz_r_out.txt\n")
