* ============================================================
* Title:   Step 0 -- AHZ smoke test via reg_sandwich
* Author:  Emilia Tjernstrom (with Claude)
* Date:    2026-05-01
* Purpose: Fit OLS on toy panel, run reg_sandwich + test_sandwich
*          for joint H0: beta_x1 = beta_x2 = beta_x3 = 0 (q=3),
*          dump AHZ statistic / df / p-value to text at full
*          precision for cross-check against R clubSandwich HTZ.
* Input:   toy_panel.csv  (generated by make_toy_panel.py)
* Output:  step0_ahz_stata.smcl
*          step0_ahz_stata_out.txt   (parsable scalars)
* ============================================================

clear all
set more off
set varabbrev off
capture log close
log using "step0_ahz_stata.smcl", replace

capture noisily {
    * Load the same toy panel R will use.
    import delimited "toy_panel.csv", clear varnames(1)

    * Sanity check.
    di as text "rows: " _N
    quietly levelsof pid, local(pids)
    local nclust : word count `pids'
    di as text "clusters: `nclust'"

    * Plain OLS with cluster-robust SE for reference (the regress fit
    * is what reg_sandwich rebuilds; we want the b's to match).
    regress y x1 x2 x3 z, vce(cluster pid)
    matrix b_ols   = e(b)
    matrix V_clu   = e(V)
    scalar N_ols   = e(N)
    scalar G_ols   = e(N_clust)

    * Hand off to reg_sandwich (BRL-FE / CR2) + test_sandwich (AHZ).
    * No absorb here: matches the unabsorbed-FE branch we'll use in
    * production.  z stays in the regression but is not in the joint
    * test.
    reg_sandwich y x1 x2 x3 z, cluster(pid)
    matrix b_rs = e(b)

    * The joint multi-parameter Wald test on (x1, x2, x3): q = 3.
    test_sandwich x1 x2 x3

    scalar F_stat   = e(F_stat)
    scalar F_df1    = e(F_df1)
    * NB: test_sandwich's help has a typo and lists e(F_df1) twice;
    * the denominator df is actually returned in e(F_df2).  Capture
    * both and we'll use whichever is non-missing.
    capture scalar F_df2_a = e(F_df2)
    capture scalar F_df2_b = e(F_df1)
    scalar F_pvalue = e(F_pvalue)
    scalar F_eta    = e(F_eta)

    di as text "----- AHZ scalars from test_sandwich -----"
    di as text "F_stat   = " %24.16e F_stat
    di as text "F_df1    = " %24.16e F_df1
    capture di as text "F_df2(e2)= " %24.16e F_df2_a
    di as text "F_pvalue = " %24.16e F_pvalue
    di as text "F_eta    = " %24.16e F_eta

    * Show all e() so we can confirm the storage names.
    ereturn list

    * Persist scalars for the cross-check at full precision.  Use
    * mata so we can write %24.16e directly.
    mata: f = fopen("step0_ahz_stata_out.txt", "w")
    mata: fput(f, sprintf("engine=stata_reg_sandwich"))
    mata: fput(f, sprintf("F_stat=%24.16e", st_numscalar("F_stat")))
    mata: fput(f, sprintf("F_df1=%24.16e",  st_numscalar("F_df1")))
    mata: fput(f, sprintf("F_df2=%24.16e",  st_numscalar("F_df2_a")))
    mata: fput(f, sprintf("F_pvalue=%24.16e", st_numscalar("F_pvalue")))
    mata: fput(f, sprintf("F_eta=%24.16e", st_numscalar("F_eta")))
    mata: fput(f, sprintf("N_obs=%24.16e", st_numscalar("N_ols")))
    mata: fput(f, sprintf("N_clust=%24.16e", st_numscalar("G_ols")))
    mata: fclose(f)

    di as text "wrote step0_ahz_stata_out.txt"
}
local saved_rc = _rc
capture log close
if `saved_rc' != 0 {
    di as error ">>> step0_ahz_stata.do FAILED with rc=`saved_rc'"
}
exit, STATA clear
