"""S3: build a caller map for every program defined in RP7/scripts/0_programs.do.

For each program, lists files that call it (anywhere in the repo except the
read-only RP6 junction at top-level `scripts/`). Output is a markdown review
at quality_reports/reviews/2026-04-30_program-caller-map.md.

A "caller" is a non-comment line that names the program. Comments are
stripped before matching: lines starting with `*` (after optional whitespace)
or content after `//`. Multi-line `/* ... */` blocks are not stripped, but
those are rare in the codebase.

Run from the project root:
    python tools/program_caller_map_phase2_s3.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROGRAMS_FILE = ROOT / "RP7" / "scripts" / "0_programs.do"
OUTPUT_FILE = ROOT / "quality_reports" / "reviews" / "2026-04-30_program-caller-map.md"

# Search trees. RP7/scripts is the active code. explorations/ holds out-of-tree
# experimental scripts. tests/ holds verification drivers. The top-level
# `scripts/` junction points to the coauthor's RP6 (read-only); excluded.
SEARCH_DIRS = [
    ROOT / "RP7" / "scripts",
    ROOT / "explorations",
    ROOT / "tests",
]

PROGRAM_DEF_RE = re.compile(r"^\s*program\s+(?:define\s+)?(\w+)", re.MULTILINE)


def strip_comments(line: str) -> str:
    """Strip Stata comments. Returns empty string for full-line comments."""
    stripped = line.lstrip()
    if stripped.startswith("*"):
        return ""
    # `//` comment-to-end-of-line, but not `///` line continuation
    idx = line.find("//")
    if idx >= 0 and not line[idx:].startswith("///"):
        line = line[:idx]
    return line


def find_programs(programs_file: Path) -> list[str]:
    text = programs_file.read_text(encoding="utf-8", errors="replace")
    return list(dict.fromkeys(PROGRAM_DEF_RE.findall(text)))


def count_in_text(program: str, text: str) -> int:
    """Count non-comment lines that name `program`, excluding define/drop lines."""
    pat = re.compile(rf"\b{re.escape(program)}\b")
    skip_def = re.compile(rf"\s*(capture\s+)?program\s+(drop|define)\s+{re.escape(program)}\b")
    n = 0
    for line in text.splitlines():
        stripped = strip_comments(line)
        if not stripped or skip_def.match(stripped):
            continue
        if pat.search(stripped):
            n += 1
    return n


def find_external_callers(program: str, search_dirs: list[Path]) -> dict[Path, int]:
    """Return {path: count} for files that call `program`, excluding 0_programs.do."""
    callers: dict[Path, int] = {}
    for d in search_dirs:
        if not d.exists():
            continue
        for path in d.rglob("*.do"):
            if path.resolve() == PROGRAMS_FILE.resolve():
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            count = count_in_text(program, text)
            if count:
                callers[path] = count
    return callers


def count_internal(program: str, programs_text: str) -> int:
    """Count occurrences of `program` inside 0_programs.do itself.

    Excludes the program's own define/drop lines. Captures helper-program
    invocations from inside other programs (e.g. data_setup -> handle_choice).
    """
    return count_in_text(program, programs_text)


def relpath(p: Path) -> str:
    return p.relative_to(ROOT).as_posix()


def write_review(
    programs: list[str],
    external: dict[str, dict[Path, int]],
    internal: dict[str, int],
) -> None:
    lines: list[str] = []
    lines.append("# Program-caller map for `RP7/scripts/0_programs.do`")
    lines.append("")
    lines.append("Phase 2, S3 deliverable from [the refactor spec](file:///"
                 f"{(ROOT / 'quality_reports' / 'specs' / '2026-04-24_grc-pipeline-refactor.md').as_posix()}).")
    lines.append("")
    lines.append("Auto-generated by [tools/program_caller_map_phase2_s3.py]"
                 f"(file:///{(ROOT / 'tools' / 'program_caller_map_phase2_s3.py').as_posix()}).")
    lines.append("")
    lines.append("Search trees for external callers:")
    for d in SEARCH_DIRS:
        marker = " (missing)" if not d.exists() else ""
        lines.append(f"- `{relpath(d)}/`{marker}")
    lines.append("")
    lines.append("Excluded: top-level `scripts/` junction (read-only RP6 view),"
                 " `paper/` (LaTeX, no Stata callers), `RP7/output/`, `data/`, build artifacts.")
    lines.append("")
    lines.append("A caller line is any non-comment occurrence of the program name; "
                 "the file's own `program define` / `capture program drop` lines are excluded.")
    lines.append("Per-file counts are line-counts, not invocation counts---a single "
                 "call spanning multiple `///`-continued lines counts once per line that names the program.")
    lines.append("")
    lines.append("**Internal calls** (column `Internal`) count occurrences inside `0_programs.do` "
                 "itself, where one program in the file invokes another (e.g. `data_setup` calls "
                 "`handle_choice`). A program with zero external callers but nonzero internal callers "
                 "is a private helper, not dead code.")
    lines.append("")
    # Summary table.
    lines.append("## Summary")
    lines.append("")
    lines.append("| Program | External | Internal | External callers |")
    lines.append("|---|---:|---:|---|")
    truly_dead: list[str] = []
    helpers: list[str] = []
    for prog in programs:
        callers = external[prog]
        ext_total = sum(callers.values())
        int_total = internal[prog]
        files = ", ".join(f"`{relpath(p)}`" for p in sorted(callers)) if callers else "_none_"
        if ext_total == 0 and int_total == 0:
            truly_dead.append(prog)
        elif ext_total == 0:
            helpers.append(prog)
        lines.append(f"| `{prog}` | {ext_total} | {int_total} | {files} |")
    lines.append("")

    if truly_dead:
        lines.append("## Programs with zero callers anywhere (candidates for deletion)")
        lines.append("")
        for prog in truly_dead:
            lines.append(f"- `{prog}`")
        lines.append("")
        lines.append("Zero external callers and zero internal callers across the active tree. "
                     "Before deletion, verify against the read-only `scripts/` (RP6) junction---a "
                     "program may be live in RP6 and only stale in RP7. "
                     "Deletion decisions belong in Phase 6, not this map.")
        lines.append("")

    if helpers:
        lines.append("## Internal-only helpers (not dead, but private)")
        lines.append("")
        for prog in helpers:
            lines.append(f"- `{prog}` ({internal[prog]} internal call lines)")
        lines.append("")
        lines.append("Zero external callers but nonzero internal references. "
                     "These are private helpers used only by other programs in `0_programs.do`. "
                     "Not dead; do not delete.")
        lines.append("")

    # Per-program detail.
    lines.append("## Per-program detail")
    lines.append("")
    for prog in programs:
        callers = external[prog]
        int_total = internal[prog]
        lines.append(f"### `{prog}`")
        lines.append("")
        lines.append(f"Internal calls inside `0_programs.do`: **{int_total}**.")
        lines.append("")
        if not callers:
            lines.append("No external callers.")
            lines.append("")
            continue
        lines.append("| External file | Lines naming the program |")
        lines.append("|---|---:|")
        for path in sorted(callers):
            lines.append(f"| [{relpath(path)}](file:///{path.as_posix()}) | {callers[path]} |")
        lines.append("")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    programs_text = PROGRAMS_FILE.read_text(encoding="utf-8", errors="replace")
    programs = find_programs(PROGRAMS_FILE)
    external = {prog: find_external_callers(prog, SEARCH_DIRS) for prog in programs}
    internal = {prog: count_internal(prog, programs_text) for prog in programs}
    write_review(programs, external, internal)
    truly_dead = [p for p in programs if not external[p] and internal[p] == 0]
    helpers = [p for p in programs if not external[p] and internal[p] > 0]
    print(f"Wrote {OUTPUT_FILE.relative_to(ROOT).as_posix()}")
    print(f"  programs:        {len(programs)}")
    print(f"  truly-dead:      {len(truly_dead)}")
    print(f"  internal-only:   {len(helpers)}")


if __name__ == "__main__":
    main()
