"""Assemble the baseline-vs-cluster-residualized GRC comparison table.

Reads the per-country GRC tables produced by the Stata pipeline and writes the
cross-country summary table used in the "Robustness to cluster pooling"
subsection. Both inputs are pipeline outputs:

  baseline phi  <- output/tables/GRC_{country}_consumption_urban_unb.tex
                   (column 5: full controls + time FE, unbalanced panel)
  cluster phi   <- output/tables/verdier_robust_onestep_{country}_consumption_urban_unb.tex
                   (column 5: onestep GMM, instruments residualized within cluster)

Output: output/tables/cluster_comparison_consumption_unb.tex

Run from RP7/scripts:  python gen_cluster_comparison_table.py
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
TABLES = os.path.join(HERE, "..", "output", "tables")

COUNTRIES = [("IDN", "Indonesia"), ("CHN", "China"), ("TZA", "Tanzania")]


def _col5(cell_line):
    """Return the fifth data cell of a Stata esttab row, stripped of the row
    terminator but keeping significance stars."""
    cells = cell_line.split("&")
    token = cells[5].strip()
    token = token.replace("\\\\", "").strip()
    return token


def parse_phi(path):
    """Extract the column-5 phi point estimate (with stars) and its standard
    error from a GRC .tex table."""
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    for i, line in enumerate(lines):
        if line.lstrip().startswith(r"$\phi$"):
            phi = _col5(line)
            se = _col5(lines[i + 1])
            return phi, se
    raise ValueError(f"No $\\phi$ row found in {path}")


def main():
    rows = []
    for code, name in COUNTRIES:
        base_phi, base_se = parse_phi(
            os.path.join(TABLES, f"GRC_{code}_consumption_urban_unb.tex")
        )
        rob_phi, rob_se = parse_phi(
            os.path.join(
                TABLES,
                f"verdier_robust_onestep_{code}_consumption_urban_unb.tex",
            )
        )
        rows.append((name, base_phi, base_se, rob_phi, rob_se))

    body = []
    for k, (name, bphi, bse, rphi, rse) in enumerate(rows):
        body.append(f"{name:<11}& {bphi:<10}& {rphi:<10}\\\\")
        body.append(f"{'':<11}& {bse:<10}& {rse:<10}\\\\")
        if k < len(rows) - 1:
            body.append(r"\addlinespace")

    tex = r"""% Generated by gen_cluster_comparison_table.py --- do not hand-edit.
\begin{table}[htb!] \centering \begin{threeparttable}
\caption{Baseline versus cluster-residualized GRC slope, consumption (unbalanced panel)}
\label{tab:verdier-robust}
\begin{tabular}{l cc} \toprule
                       & \multicolumn{1}{c}{Baseline $\hat\phi$}
                       & \multicolumn{1}{c}{Cluster-residualized $\hat\phi^{\mathrm{rob}}$} \\
\midrule
""" + "\n".join(body) + r"""
\bottomrule
\end{tabular}
\begin{tablenotes}[flushleft] \footnotesize
\item{Both columns report the LCA slope $\phi$ from the restricted GRC on the unbalanced consumption sample with full controls and period fixed effects (column~(5) of the per-country GRC tables). The baseline column reproduces the pooled estimate; the cluster-residualized column re-estimates $\phi$ after replacing the switcher-treatment instruments with their within-cluster residuals, using onestep GMM. Cluster-residualized standard errors are clustered at the level of the cluster of first observation (first-wave province in Indonesia and China, region in Tanzania); baseline standard errors follow the main specification. Stars: $^{*}p<0.10$; $^{**}p<0.05$; $^{***}p<0.01$.}
\end{tablenotes} \end{threeparttable} \end{table}
"""

    out = os.path.join(TABLES, "cluster_comparison_consumption_unb.tex")
    with open(out, "w", encoding="utf-8") as f:
        f.write(tex)
    print("wrote", os.path.normpath(out))
    for name, bphi, bse, rphi, rse in rows:
        print(f"  {name:<11} baseline {bphi:>10} ({bse})   cluster {rphi:>10} ({rse})")


if __name__ == "__main__":
    main()
