"""Build the Verdier robust onestep-vs-twostep comparison from the 6 paper tables.

Parses RP7/output/tables/verdier_robust_{step}_{country}_consumption_urban_unb.tex
(generated by 17_verdier_robust.do via grc_tex_table_trend) and writes a
markdown summary to quality_reports/reviews/2026-04-29_verdier-v2-onestep-vs-twostep.md
plus a tidy CSV alongside it.

Replaces the Stata `file write` block that kept truncating mid-stream (file flush
threw r(198) in the project's Stata version, and `estimates restore` on names
that were never `eststo`'d cascaded into r(111) from `_b[Delta_never:_cons]`).

Numbers come from the same .tex tables that go into the paper, so what you read
in the comparison is exactly what the paper reports.
"""

from __future__ import annotations

import csv
import re
from pathlib import Path

WORKTREE = Path(__file__).resolve().parents[2]
TABLES = WORKTREE / "RP7" / "output" / "tables"
OUT_MD = WORKTREE / "quality_reports" / "reviews" / "2026-04-29_verdier-v2-onestep-vs-twostep.md"
OUT_CSV = OUT_MD.with_suffix(".csv")

COUNTRIES = [("IDN", "Indonesia"), ("TZA", "Tanzania"), ("CHN", "China")]
STEPS = ["onestep", "twostep"]
SPECS = ["covs_0", "covs_trend", "covs_1", "covs_2", "covs_all"]
SPEC_LABELS = {
    "covs_0":     "(1) no FE, no covs",
    "covs_trend": "(2) + time FE",
    "covs_1":     "(3) + female",
    "covs_2":     "(4) + age^2",
    "covs_all":   "(5) + education",
}

# Strip latex stars/spaces from a coefficient cell.
_STAR_RE = re.compile(r"\*+$")
def _clean_cell(cell: str) -> str:
    s = cell.strip().rstrip("\\").strip()
    s = _STAR_RE.sub("", s).strip()
    return s


def _split_columns(line: str) -> list[str]:
    """Split a LaTeX table row on `&`, dropping the leading label and trailing `\\`."""
    body = line.rstrip().rstrip("\\").rstrip()
    parts = [p.strip() for p in body.split("&")]
    return parts


def parse_table(path: Path) -> dict[str, list[str]]:
    """Pull the rows we care about out of one verdier_robust table.

    Returns a dict mapping logical row name -> list of 5 strings (one per spec).
    Coefficient cells are returned without stars; SE cells keep the parentheses.
    Missing values render as ``"."`` from Stata; we keep them as-is.
    """
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    # Order matters: longer labels first so "J-stat (p-value)" is not shadowed by "J-stat".
    wanted = [
        (r"$\Delta_{\text{never}}$", "delta_never_b"),
        ("Average $\\Delta$",        "delta_avg_b"),
        ("$\\phi$",                  "phi_b"),
        ("Individuals",              "n_individuals"),
        ("Observations",             "n_obs"),
        ("J-stat (p-value)",         "j_pval"),
        ("J-stat",                   "j_stat"),
        ("Converged",                "converged"),
    ]

    out: dict[str, list[str]] = {}
    se_buffer: dict[str, list[str]] = {
        "delta_never_se": [],
        "delta_avg_se":   [],
        "phi_se":         [],
    }

    last_b_row: str | None = None  # which b-row we just saw, so the next SE row attaches
    b_to_se = {
        "delta_never_b": "delta_never_se",
        "delta_avg_b":   "delta_avg_se",
        "phi_b":         "phi_se",
    }

    for line in lines:
        stripped = line.lstrip()
        # Match coefficient rows by their leading label.
        matched = False
        for label, key in wanted:
            if stripped.startswith(label):
                # Splitting on `&` yields cols[0] = empty (before the first &),
                # cols[1..5] = the 5 spec columns, optional cols[6] = trailing junk.
                cols = _split_columns(stripped[len(label):])
                values = [_clean_cell(c) for c in cols[1:6]]
                while len(values) < 5:
                    values.append(".")
                out[key] = values
                last_b_row = key if key in b_to_se else None
                matched = True
                break
        if matched:
            continue

        # SE row: starts with whitespace then `&` and a parenthesised number.
        if last_b_row is not None and stripped.startswith("&"):
            cols = _split_columns(stripped)
            # cols[0] is empty (label is empty), the rest are the SE cells.
            values = [_clean_cell(c) for c in cols[1:6]]
            while len(values) < 5:
                values.append(".")
            se_key = b_to_se[last_b_row]
            se_buffer[se_key] = values
            last_b_row = None

    out.update(se_buffer)
    return out


def render_country_block(country_code: str, country_name: str) -> tuple[list[str], list[dict]]:
    """Return (markdown_lines, csv_rows) for one country."""
    md: list[str] = []
    rows: list[dict] = []
    md.append(f"## {country_name} ({country_code})")
    md.append("")
    md.append(
        "| Spec | Step | phi | Delta_never | Delta_avg | J | J p | N indiv | N obs | Conv |"
    )
    md.append(
        "|------|------|-----|-------------|-----------|---|-----|---------|-------|------|"
    )

    by_step = {}
    for step in STEPS:
        path = TABLES / f"verdier_robust_{step}_{country_code}_consumption_urban_unb.tex"
        if not path.exists():
            md.append(f"| MISSING TABLE: {path.name} |  |  |  |  |  |  |  |  |  |")
            continue
        by_step[step] = parse_table(path)

    for spec_idx, spec in enumerate(SPECS):
        for step in STEPS:
            data = by_step.get(step)
            if data is None:
                continue
            phi    = f"{data['phi_b'][spec_idx]} {data['phi_se'][spec_idx]}".strip()
            d_nev  = f"{data['delta_never_b'][spec_idx]} {data['delta_never_se'][spec_idx]}".strip()
            d_avg  = f"{data['delta_avg_b'][spec_idx]} {data['delta_avg_se'][spec_idx]}".strip()
            j      = data["j_stat"][spec_idx] or "."
            jp     = data["j_pval"][spec_idx] or "."
            n_ind  = data["n_individuals"][spec_idx]
            n_obs  = data["n_obs"][spec_idx]
            conv   = data["converged"][spec_idx]
            md.append(
                f"| {SPEC_LABELS[spec]} | {step} | {phi} | {d_nev} | {d_avg} | {j} | {jp} | {n_ind} | {n_obs} | {conv} |"
            )
            rows.append({
                "country": country_code,
                "step": step,
                "spec": spec,
                "spec_label": SPEC_LABELS[spec],
                "phi_b": data["phi_b"][spec_idx],
                "phi_se": data["phi_se"][spec_idx],
                "delta_never_b": data["delta_never_b"][spec_idx],
                "delta_never_se": data["delta_never_se"][spec_idx],
                "delta_avg_b": data["delta_avg_b"][spec_idx],
                "delta_avg_se": data["delta_avg_se"][spec_idx],
                "j_stat": j,
                "j_pval": jp,
                "n_individuals": n_ind,
                "n_obs": n_obs,
                "converged": conv,
            })
    md.append("")
    return md, rows


def main() -> None:
    md: list[str] = []
    md.append("# Verdier robust estimator: onestep vs twostep comparison")
    md.append("")
    md.append("Generated by `gen_verdier_comparison.py` from the 6 paper .tex tables.")
    md.append("Spec: log per-capita consumption, urban as treatment, unbalanced panel.")
    md.append("Numbers are identical to what `17_verdier_robust.do` writes into")
    md.append("`RP7/output/tables/verdier_robust_{onestep,twostep}_{IDN,TZA,CHN}_consumption_urban_unb.tex`.")
    md.append("")
    md.append("Each block reports phi, Delta_never, Delta_avg (b followed by SE in parens),")
    md.append("Hansen J + p-value (twostep only; blank under onestep), individual count, observation count,")
    md.append("and `e(converged)` (Y/N) for the main GMM call.")
    md.append("")
    md.append("Spec key: ")
    for s in SPECS:
        md.append(f"- {SPEC_LABELS[s]}")
    md.append("")

    all_rows: list[dict] = []
    for code, name in COUNTRIES:
        block, rows = render_country_block(code, name)
        md.extend(block)
        all_rows.extend(rows)

    md.append("## How to read this")
    md.append("")
    md.append("- Pick onestep vs twostep per country. Working hypothesis: twostep when J is finite and")
    md.append("  the cell converged; otherwise onestep. SEs clustered at the village (vfirst) level.")
    md.append("- A blank J / J p means twostep did not converge (Stata cannot compute Hansen J without")
    md.append("  a valid weighting matrix at the optimum); fall back to onestep for that cell.")
    md.append("- Convergence column reports `e(converged)` for the main GMM call. `N` does NOT")
    md.append("  necessarily disqualify the cell --- check the .ster manually if you care.")
    md.append("")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(md) + "\n", encoding="utf-8")

    fieldnames = list(all_rows[0].keys()) if all_rows else []
    with OUT_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(all_rows)

    print(f"Wrote {OUT_MD}")
    print(f"Wrote {OUT_CSV}")
    print(f"{len(all_rows)} rows across {len(COUNTRIES)} countries x {len(STEPS)} steps x {len(SPECS)} specs.")


if __name__ == "__main__":
    main()
